version: '3.1'
services:
  devbox:
    image: "healthsamurai/devbox:canary"
    command: ["wait-for-it.sh", "database:5432", "--strict", "--timeout=0", "--", "java", "-jar", "/app.jar"]
    depends_on:
      - devbox-db
    links:
      - "devbox-db:database"
    ports:
      - "8888:8888"
    environment:
      AIDBOX_FHIR_VERSION: 4.0.0
      AIDBOX_PORT: 8888
      AIDBOX_LICENSE_ID: $AIDBOX_LICENSE_ID
      AIDBOX_LICENSE_KEY: $AIDBOX_LICENSE_KEY
      AIDBOX_CLIENT_ID: root
      AIDBOX_CLIENT_SECRET: secret
      AIDBOX_BASE_URL: http://127.0.0.1:8888
      PGHOST: database
      PGDATABASE: devbox
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      AIDBOX_CONFIG: /var/config/config.edn
    volumes:
      - ./example/wait-for-it.sh:/usr/local/bin/wait-for-it.sh
      - ./example/config:/var/config
  devbox-db:
    image: "aidbox/db:11.1.0"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       devbox
